servers:
  default: &defaults
    channels:
    - bot-commands
    greetingChannel:
      portal
    generators:
    - beast
    - potion
    - wand
    - name
    - loot
    - encounter
    strings: &defaultStrings
      roleChange:
        '{0}, you are now a {1}.'
      roleClear:
        '{0}, your {1} has been cleared.'
      diceResults:
        '{0}, the fates have spoken: {1}, for a total of {2}.'
      rerole:
        'Another peek at my crystal ball... {0}, are you perhaps a {1}?'
      left:
        '{0} has left the server.'
  '443869685054701569': &realm
    name: The Realm
    channels:
    - '445271158502457345'
    - '447948663168303105'
    - '503463950243987486'
    - '542141314536439808'
    - '566381413491015701'
    - '597065299124289552'
    - 'bot-commands'
    - 'adventures-in-pevar-ooc'
    - 'starships-and-sorcerers-ooc'
    defaultRoleset: creature
    automod:
      channel: 'the-dungeons'
      role: 'In the Dungeons!'
    rolesets:
      creature:
        Dwarf:
          secondaryRoles:
          - Humanoids
        Elf:
          secondaryRoles:
          - Humanoids
        Fairy:
          secondaryRoles:
          - Humanoids
        Giant:
          secondaryRoles:
          - Humanoids
        Goblin:
          secondaryRoles:
          - Humanoids
          random: False
        Gnome:
          secondaryRoles:
          - Humanoids
        Halfling:
          secondaryRoles:
          - Humanoids
        Human:
          secondaryRoles:
          - Humanoids
        Mermaid:
          secondaryRoles:
          - Humanoids
          random: False
        Vampire:
          secondaryRoles:
          - Humanoids
        Werewolf:
          secondaryRoles:
          - Humanoids
        Witch:
          secondaryRoles:
          - Humanoids
          random: False
        Wizard:
          secondaryRoles:
          - Humanoids
          random: False
        Zombie:
          secondaryRoles:
          - Humanoids

        Basilisk:
          secondaryRoles:
          - Beasts
        Chimera:
          secondaryRoles:
          - Beasts
        Centaur:
          secondaryRoles:
          - Beasts
        Cyclops:
          secondaryRoles:
          - Beasts
        Dragon:
          secondaryRoles:
          - Beasts
        Gryphon:
          secondaryRoles:
          - Beasts
        Loch Ness Monster:
          secondaryRoles:
          - Beasts
        Ogre:
          secondaryRoles:
          - Beasts
          random: False
        Orc:
          secondaryRoles:
          - Beasts
          random: False
        Pegasus:
          secondaryRoles:
          - Beasts
        Phoenix:
          secondaryRoles:
          - Beasts
        Sasquatch:
          secondaryRoles:
          - Beasts
          random: False
        Sphinx:
          secondaryRoles:
          - Beasts
        Unicorn:
          secondaryRoles:
          - Beasts

        Angel:
          secondaryRoles:
          - Spirits
        Ascended:
          secondaryRoles:
          - Spirits
        Banshee:
          secondaryRoles:
          - Spirits
          random: False
        Demon:
          secondaryRoles:
          - Spirits
        Deity:
          secondaryRoles:
          - Spirits
        Djinn:
          secondaryRoles:
          - Spirits
        Ghost:
          secondaryRoles:
          - Spirits
        Ghoul:
          secondaryRoles:
          - Spirits
        Grim:
          secondaryRoles:
          - Spirits
        Kobold:
          secondaryRoles:
          - Spirits
        Poltergeist:
          secondaryRoles:
          - Spirits
        Skeleton:
          secondaryRoles:
          - Spirits
        Sylph:
          secondaryRoles:
          - Spirits
        Wraith:
          secondaryRoles:
          - Spirits
        removeOnUpdate:
        - Beasts
        - Spirits
        - Humanoids
      class:
        Barbarian:
          description: A warrior from the wilds who draws strength from his rage.
        Bard:
          description: A performer of such skill that their performances can have magical effects.
        Brawler:
          description: A fighter who relies on brawn and street smarts rather than grueling training.
        Cleric:
          description: A priest of a specific deity or pantheon. Best known for their healing magic.
        Druid:
          description: A magic user deeply in tune with nature. Can often transform into animals.
        Fighter:
        Mage:
          description: A skilled magic user who has studied or been granted the arcane arts.
        Monk:
          description: An agile warrior trained in the martial arts of a faraway land.
        Paladin:
          description: A holy knight, gifted with both physical prowess and holy magic.
        Ranger:
          description: A tracker, hunter, and/or woodsman. May know some relevant magic.
        Rogue:
          description: A thief or assassin. Quick, sneaky, and best not let out of your sight.
        Soldier:
          description: A disciplined warrior accustomed to fighting together with their comrades-in-arms.
        Sorceror:
        Warlock:
    strings:
      invalidcreature:
        '{0}, role {1} is not on the valid list. Perhaps have a look at my bestiary with `!creature`, or I can choose for you with `!rerole`.'
      invalidclass:
        '{0}, role {1} is not on the valid list. You can see the options with `!class`.'
      welcome:
        'Welcome to The Realm, {0}. You seem to be a ... {1}, perhaps? My crystal ball has been foggy of late. If I''m wrong, quest to the pinned message in <#445271158502457345> to change your character, adventurer!'
      creatureRoleList:
        'Have a look at my bestiary. You may be one of these, just say `!creature creaturename`. For instance, `!creature dragon`'
      classRoleList:
        'Looking for a career change, eh? {0}... Take your pick of these with `!class classname`. For instance, `!class soldier`'
      <<: *defaultStrings
    static:
      spank: https://i.imgur.com/3ZERxgc.png
      charge: https://cdn.discordapp.com/attachments/444030298406125568/503820387864281089/annoyedcatTim2.png
    scheduled:
    - time: 2018-12-30T12:00
      channel: command-line
      message: This message is left solely as a syntax reminder. As it is in the past, it should never trigger.
    <<: *defaults
  '489197880809095168':
    <<: *realm
  '494373430637101058':
    name: Test
    defaultRoleset:
      element
    rolesets:
      element:
        Solar:
        Lunar:
        Gaian:
      job:
        Soldier:
        Mage:
        Archer:
    strings:
      welcome:
        'Welcome, {0}. You have an aura of {1} magic around you. If you''d like to change it, see the pinned message in <#494374610545147905>.'
      elementRoleList:
        'The elements are as follows: {0}. You may choose your alignment with "!element elementname".'
      jobRoleList:
        'The jobs are as follows: {0}. You may choose your job with "!job jobname".'
      rerole:
        'Another peek at my crystal ball... {0}, are you attuned to {1} magic?'

      <<: *defaultStrings
    <<: *defaults
  '570788677937135626':
    name: Just Write
    channels:
    - tims-room
    - '570800943529197578'
    <<: *defaults
  '566868285791010827':
    name: Kittens & Unicorns
    channels:
    - beep-boop
    - '566880416833732613'
    - chatter
    - '566875832770101269'
    - rant
    - '566876681806020630'
    - guillotine
    - '579019008591003655'
    automod:
      channel: 'bridge'
      role: 'troll'
    lmgtfyDefault: d
    recurring:
    - time: R/2019-08-29T00:00Z/PT6H
      channel: rainbow
      message: bump https://discord.me/dashboard
    leavingChannel: rainbow
    <<: *defaults
